# Generated by Django 5.1.1 on 2024-10-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('cause', models.TextField()),
                ('full_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('invoice_url', models.URLField()),
            ],
        ),
    ]
